version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myapp